module:
  _target_: equivariance_measure.embedding_distances.EmbeddingDistanceModule
  num_classes: 1000
  pretrained: True
  results_dir: ${results_dir}
  data_stage: ${data_stage}
  prefix: ""

data_module:
  _target_: equivariance_measure.data.ImageNetNoAugDataModule
  data_dir: path_to_image_net
  num_workers: 16
  batch_size: 32

name: invariance_measure
data_stage: train
n_batches: 300
random_seed: 0
results_dir: /checkpoint/${env:USER}/Real-Data-Equivariance/results/${name}_${n_batches}_batches

hydra:
  job:
    name: ${name}